### PR TITLE
Add non blocking and back pressure support

### PR DESCRIPTION
**Pull request by wburns**
Required Protocols (rest are not needed unless optional such as ENCRYPT)
* some type of PING
* FD_ALL3
* VERIFY_SUSPECT ?
* NAKACK2 required for digest in GMS (mark message as no reliability)
* GMS
* MERGE

Other Notes

* FD_SOCK is doable in the transport but not done yet
* Support for non blocking messages uses NettyAsyncHeader and
MessageCompleteEvent
* Add MemberAvailabililtyEvent to notify users of back pressure
* Add Normal message processor with back pressure
* Fix replaying to work with messages not containing all bytes
* Send OOB and Normal messages on different sockets
* Fix concurrent client connections
* Allow injection of event loop groups to use
* Allow injection of socket channels to use

### CODE REVIEW

**Comment by wburns** [comment]
Just wanted to update you with the changes I have so far @belaban and see what feedback you may have in this regard.

**Comment by wburns** [comment]
The second commit can be ignored for now as it requires more work, but basically this is to support a ByteBufMessage type that can support no additional copy to/from the socket for message processing. This requires more reworking because everything in JGroups currently requires byte[] so I have to circumvent some method calls.

**Comment by wburns** [comment]
Also I eliminated the worker thread group so everything in the response is processed on the event loop for that socket. The on unfortunate effect of this is that normal messages are slightly slower when only a single node generates traffic as the processing of the message delays the socket read, but under multiple message senders it was scaling better in my tests.

**Comment by belaban** [comment]
I'll take a look, give me a few days

**Comment by belaban** [comment]
I get an NPE: `isOOB` is set in `down(Message)`, but the thread actually sending the message is a different one (from `TransferQueueBundler`).
I tried to use `Draw` to test a cluster, but `netty.xml` requires changes, e.g. `Netty` -> `NettyTP` etc... which test do you use?

**Comment by wburns** [comment]
> I get an NPE: `isOOB` is set in `down(Message)`, but the thread actually sending the message is a different one (from `TransferQueueBundler`). I tried to use `Draw` to test a cluster, but `netty.xml` requires changes, e.g. `Netty` -> `NettyTP` etc... which test do you use?

I am currently using a new branch in upstream ISPN to test.

The only bundler that is supported with this is NoBundler `bundler_type="no-bundler"`. I forgot to force that bundler in the NettyTP.

My stack is as the follows:

```xml
   <netty.NettyTP bind_addr="${jgroups.bind.address,jgroups.tcp.address:SITE_LOCAL}"
                  bind_port="${jgroups.bind.port,jgroups.tcp.port:7800}"
                  bundler_type="no-bundler"
   />
   <MPING mcast_addr="${jgroups.mcast_addr:239.6.7.8}"
          mcast_port="${jgroups.mcast_port:46655}"
          num_discovery_runs="3"
          ip_ttl="${jgroups.udp.ip_ttl:2}"
   />
   <MERGE3 min_interval="10000"
           max_interval="30000"
   />
   <FD_ALL3/>
   <VERIFY_SUSPECT2 timeout="1000"/>
   <pbcast.NAKACK2 use_mcast_xmit="false"
                   xmit_interval="200"
                   xmit_table_num_rows="50"
                   xmit_table_msgs_per_row="1024"
                   xmit_table_max_compaction_time="30000"
                   resend_last_seqno="true"
   />
   <pbcast.GMS print_local_addr="false"
               join_timeout="${jgroups.join_timeout:2000}"
               view_ack_collection_timeout="1"
   />
   ```
   
   I can clean up the branch more and get Draw working.

**Comment by wburns** [comment]
NAKACK2 is only there for the DIGEST messages for GMS. In ISPN I set all of our messages to have NO_RELIABILITY
```java
      if (nettyTP != null) {
         message.setFlag(Message.Flag.NO_RELIABILITY);
      }
```

**Comment by wburns** [comment]
I was now able to use the UPerf test `./run.sh org.jgroups.tests.perf.UPerf -props netty.xml` and found that with the default size of 1KB the new transport for faster than TCP in clusters from size 2 to 5. Cluster size 2 especially saw a very large difference on my laptop.

```
Throughput: 257,037.02 reqs/sec/node (257.04MB/sec)
Roundtrip:  gets avg = 322.13 us, puts avg = 642.60 us
```
vs
```
Throughput: 194,566.77 reqs/sec/node (194.57MB/sec)
Roundtrip:  gets avg = 446.29 us, puts avg = 764.37 us
```

One thing to note is that while UPerf works before my changes the actual messages are completely messed up due to a race condition with reading and writing to the same byte[] at https://github.com/jgroups-extras/jgroups-netty/blob/master/src/main/java/netty/utils/ReceiverHandler.java#L21. Since this handler is shared with all channels all sockets will write to the same byte[] before passing of the message.

**Comment by wburns** [comment]
Fixing some issues that I messed up with the recent commit.. UPerf should still work though.

**Comment by wburns** [comment]
Updated to fix mcast and also reuse the same buffer even if the message is not a ByteBufMessage

**Pull request merged**
